### ISSUE TITLE
Interest to use extracted modemtalk?

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/pc-nrfconnect-linkmonitor#18]
Hei @bencefr,

I have extracted the modemtalk library into a standalone module, so I could use it in a CLI I wrote for flashing credentials: https://github.com/bifravst/modemtalk

Are you interested in this and should I start on moving this forward, specifically:

- [x] move the repo to the official NordicSemiconductor organization
- [x] publish ~~under NordicSemiconductor npm organization~~ on npm: https://www.npmjs.com/package/modemtalk
- [x] remove modemtalk from this repo: https://github.com/NordicSemiconductor/pc-nrfconnect-linkmonitor/pull/29
- [x] use the external module instead

**Comment by bencefr** [comment]
Hi @coderbyheart ,

Sure I am interested. This was the original idea, only kept it in linkmonitor for easier updates until it got stable.

**Comment by coderbyheart** [comment]
Great, how stable would you consider it?

**Comment by bencefr** [comment]
Well, it works now. It would require more testing against hardware/firmware/modem, since the behaviour of those were evolving too. To be more specific e.g. timeouts can confuse this library.
There's a builtin logic to talk to the modem in a sequential manner. I think that one should not send any command to the modem before response is received for the previous one. And even this is not a hard rule, nonetheless I forced this. So, timeouts could be revised, maybe the some naming convention or format of expected results. These were never really unified or set in stone.
Also for reference we could commit our AT-command documentation.

**Comment by coderbyheart** [comment]
@bencefr #29 is ready for review
